### ISSUE TITLE
Caching files for Spark

### ISSUE THREAD

**Issue by eric-czech** [ContinuumIO/intake-spark#6]
What is the best way to cache a file for the spark_dataframe driver?  I'm guessing this has a very simple answer, but I'm struggling to see it as a new user.  I don't see a way to connect `urlpath` to the generic caching mechanisms in intake (since the Spark drivers don't take that arg) and the drivers don't use fsspec, so `simplecache` is out.

All I'd like to do is point a `spark_dataframe` driver at this json file: https://storage.googleapis.com/open-targets-data-releases/20.04/input/evidence-files/eva-2020-03-20.json.gz.  I'd like intake to manage the local download and caching, and then have Spark read it locally.  Is there a straightforward way to do it?

Even more ideally, the downloaded file would be converted to parquet (also locally) and then linked from the catalog that way.  Should I just manage this kind of thing in building the catalog rather than having intake do it on `.read` or `.to_spark`?

Thanks!

**Comment by martindurant** [comment]
This idea does indeed fall between a few stools.

- I don't know if spark itself has any way to download and cache a remote dataset. In spark-world, I imagine that would mean writing to HDFS and/or Hive
- the "old" caching method in Intake could be invoked in the spark driver to make a local path out of the file, but this would not help other drivers that have a `to_spark` method, since the name of the argument might be different each time.
- spark, of course, interprets the URL itself, so there is no opportunity to insert fsspec into the mix, unless we alter the spark driver to always call `fsspec.open_local`, which will make the local path (and not allow spark to work directly on the remote data)
- the `.persist()` feature of an intake data source does something like you want, loading the remote data (using dask) into a dataframe and writing this as parquet dataset locally, which will be used in preference to the original, if it has not expired. You could call `to_spark` on this, I think. Alternately, `.export()` allows you to do this by hand to place the parquet wherever you want and gey a YAML stub back to build a catalogue from.

Finally, it is certainly unusual to run spark in a single-node setup, which is what I think you mean. Dask does this well, but spark has higher latency and overheads (especially when called from python). Maybe just use Dask? Actually, I notice that there isn't a JSON driver at all, but given that Dask's [`read_json`](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.read_json) exists, it would be easy to make.

**Comment by eric-czech** [comment]
Thanks @martindurant!  

Good to know that I wasn't missing something easy.  I certainly agree that downloading from cloud storage for Spark in local mode isn't normal, but it ends up being a practical option for one of our workloads.  I say that because many of the data sources are small to medium scientific dbs denormalized into single files (json/xml).  They're generally big enough that out-of-core processing is important, not big enough for distributed clusters, and contain nesting that Dask/Pandas/Arrow can't handle (e.g. here's one such [schema](https://nbviewer.jupyter.org/github/related-sciences/platform-pipe/blob/master/notebooks/analysis/uniprot.ipynb#schema)).  We do though use Dask for a good number of other things.

Anyways this workload between stools aside (love that), the old caching mechanism sounds like it would work.  I was trying to figure out how to use it, but couldn't tell what `argkey` should be with these spark drivers.  

I'd rather not start building on a deprecated feature too so can I ask why it would be phased out if not all intake driver projects have a way to use fsspec to replace the caching functionality?

**Comment by martindurant** [comment]
Whether the old cache or the new, the driver needs to know about it (i.e., an explicit call to process and replace the URL from the cache store), and the case of general spark operations, I'm not sure whether you can find the right URL key to replace, and you are finding. I can't immediately think of a way forward on this one.

**Comment by martindurant** [comment]
As to "why it's being deprecated" - we found that most people had a pretty hard time setting it up right, and that the cacheing mechanisms other than simple file often broke and were hard to test; also, that the drives needed to account for and call the cache code. With fsspec, the only requirement is that the target library support file-like objects (which is common) or that it is a dask implementation (which already knows about fsspec) *or* that the driver code calls open_local for libraries that require remote files to be cached.

**Comment by eric-czech** [comment]
Thanks @martindurant, I'll try making a driver then.  

Last question though and then I'll close this out: 

If I wanted to make schemas for tables containing lots of nested fields available in the intake GUI, is there a way to do that based on how I generate a `intake.source.base.Schema` instance in a driver?  Or should I make the schemas a catalog `metadata` property?

**Comment by martindurant** [comment]
The GUI only shows the "entry" information, without instantiating the source (which can incur some cost); so you need to include the information in the metadata. However, if you generate the entries in code by writing a catalog driver, then you have full control over how those entries are made and you can include whatever runtime metadata you like.
The intake GUI is pretty simple and shows the whole entry spec as a YAML block, you might even want to make your own display, if your data structure is complex enough. Having a "get schema" or "get first 10 rows" would be very reasonable things for the GUI, at the risk of making an already-busy layout even more cramped.

**Comment by eric-czech** [comment]
Good to know.   I saw that you can modify the metadata like that and thought that it looked very helpful.  I'm all set here then -- making a custom driver was easy enough given all the docs.  Thanks for you help!

**Comment by martindurant** [comment]
You are welcome to propose to include a link to your driver at https://intake.readthedocs.io/en/latest/plugin-directory.html , if you can make it public and think other might find it useful.
